# Generated by Django 5.0.4 on 2024-05-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
